server:
  port : 8082
spring:
  profiles:
    active: local
  application:
    name: service-B
  sleuth:
    propagation:
      type: B3 #,W3C
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411